# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aipad < Formula
  desc "AIPad manages context switching between AI assistants"
  homepage "https://github.com/heruujoko/aipad"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heruujoko/aipad/releases/download/v0.0.1/aipad_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "cbbeb618b7160effbac323fbec48ebf3a3655199be870ecfc844b629be98726d"

      def install
        bin.install "aipad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heruujoko/aipad/releases/download/v0.0.1/aipad_0.0.1_Darwin_arm64.tar.gz"
      sha256 "1a253ff623d1d10340238648316eeac6aa20dd94cb2e9ddc7070ab4c4c593fa1"

      def install
        bin.install "aipad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heruujoko/aipad/releases/download/v0.0.1/aipad_0.0.1_Linux_x86_64.tar.gz"
      sha256 "d0b5ffd4693d82fedc0e536d5b144fca0992c74a8d9f2f1dca22e909d6e0713e"
      def install
        bin.install "aipad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heruujoko/aipad/releases/download/v0.0.1/aipad_0.0.1_Linux_arm64.tar.gz"
      sha256 "87ceafcc40abae4863a330690c648f7ab346a6bb72a6b73a909705f81d0657c6"
      def install
        bin.install "aipad"
      end
    end
  end

  test do
    system "#{bin}/aipad --version"
  end
end
