# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Persona < Formula
  desc "Persona Sync Tool"
  homepage "https://github.com/heruujoko/persona"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heruujoko/persona/releases/download/v0.0.1/persona_Darwin_x86_64.tar.gz"
      sha256 "436bdbfd4c236a4dc338d4a6658e82e1ad4f02912102d98072e62aee7539409f"

      def install
        bin.install "persona"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heruujoko/persona/releases/download/v0.0.1/persona_Darwin_arm64.tar.gz"
      sha256 "e273036cecb17f21a8f854d1372d1fee1153b379f0e23e9b28b73192780bb60f"

      def install
        bin.install "persona"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heruujoko/persona/releases/download/v0.0.1/persona_Linux_x86_64.tar.gz"
      sha256 "56770d2ce1e807e2fe544f935910c5c3999e5d09f0b24946dab785f19a4de839"
      def install
        bin.install "persona"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heruujoko/persona/releases/download/v0.0.1/persona_Linux_arm64.tar.gz"
      sha256 "d3410d62de3aff86dccdc9623e75650068b37a001dedb57261ae963e94c1a038"
      def install
        bin.install "persona"
      end
    end
  end
end
